rootdir/init.yoshino.pwr.rc
We had MSM8996 parameters in there and.. for 8998
we need different params.
=> [YOSHINO] Fix dynamic memory bus latency parameters

rootdir/system/etc/audio_platform_info.xml
This is necessary because Sony's stock HALs have these mappings
hardcoded, while open source HALs have generic QCOM mappings.
This includes both CAF and AOSP versions.
=> [YOSHINO] Add custom ACDB IDs mapping for OSS audio HALs

rootdir/ueventd.yoshino.rc
This is needed for DRS to work.
=> [YOSHINO] ueventd: Add permissions to fb0 node for Dynamic Resolution Switch

rootdir/init.yoshino.rc
Regardless the value passed to this attribute, ZRAM will always
allocate multiple compression streams - one per online CPUs - thus
allowing several concurrent compression operations. The number of
allocated compression streams goes down when some of the CPUs
become offline. There is no single-compression-stream mode anymore,
unless you are running a UP system or has only 1 CPU online.
Change-Id: I8997d92265308c962e0ac9b4119be567c4898988
=> [master] sony: yoshino: Increase max number of compression streams

rootdir/init.yoshino.rc
daemon fingerprint is not more on android oreo it was replaced by android.hardware.biometrics.fingerprint
=> yoshino: remove not needed fingerprint service

rootdir/init.yoshino.pwr.rc
maple:/dev/cpuctl # ls
cgroup.clone_children  cgroup.sane_behavior  cpu.rt_runtime_us  cpu.upmigrate_discourage  release_agent
cgroup.procs           cpu.rt_period_us      cpu.shares         notify_on_release         tasks
also remove not existent ondemand governor paths
=> yoshino: fix init power paths

rootdir/system/etc/audio_platform_info.xml
needed by maple to run audio on stereo mode after commit 992aa870ca89f08214d3aef5490e1e67d36e2a0d
=> yoshino: set headphones acdb_id map

rootdir/init.yoshino.rc
correct soc range for octa core is 0-7 not 0-8
preserve core 3 little core for camera
=> yoshino: fix cpuset

rootdir/ueventd.yoshino.rc
maple:/sys/devices/soc/800f000.qcom,spmi/spmi-0/spmi0-03/800f000.qcom,spmi:qcom,pmi8998@3:qcom,leds@d000/leds # ls
led:rgb_blue  led:rgb_green  led:rgb_red
(led:rgb_blue led:rgb_green led:rgb_red) needs blink permissions
maple:/sys/devices/soc/800f000.qcom,spmi/spmi-0/spmi0-03/800f000.qcom,spmi:qcom,pmi8998@3:qcom,leds@d300/leds # ls
led:flash_0  led:flash_1  led:switch_0  led:torch_0  led:torch_1
remove (led:flash_0 led:flash_1 led:switch_0 led:torch_0 led:torch_1) paths
add lcd-backlight permissions
also remove double /dev/btpower path and perms
=> yoshino: fix leds

rootdir/system/etc/audio_platform_info.xml
based on CAF https://source.codeaurora.org/quic/la/platform/hardware/qcom/audio/tree/configs/msm8998/audio_platform_info.xml?h=audio-userspace.lnx.3.0.r2-rel
cleanup unused SDN_DEVICES on AudioHAL AOSP
compare these removes from aosp https://android.googlesource.com/platform/hardware/qcom/audio/+/android-8.0.0_r9/hal/msm8974/platform.c
compare these removes from caf  https://source.codeaurora.org/quic/la/platform/hardware/qcom/audio/tree/hal/msm8974/platform.c?h=audio-userspace.lnx.3.0.r2-rel
=> yoshino: update audio_platform_info.xml

Android.mk
The filter-out version was not null proof.
In case of PRODUCT_PLATFORM being unset (for example when building a non sony device with Sony trees local) the filter-out condition was falsely turning true and called all sub-makefiles, which is obviously nothing we want.
=> yoshino: Use standard ifeq in Android.mk

rootdir/init.yoshino.rc
already defined in common
see: https://github.com/sonyxperiadev/device-sony-common/blob/master/rootdir/init.common.rc#L168
=> yoshino: remove duplicated entries

platform.mk
needed for USB tethering usecase
=> yoshino: add sys.usb.rndis.func.name prop

sepolicy_platform/file_contexts
This is used by the common rdclean.sh rules, see device/sony/common
for the details.
Signed-off-by: Oleksiy Avramchenko <oleksiy.avramchenko@sony.com>
=> yoshino: label ramdump partition

rootdir/init.yoshino.rc
In order to write the WLAN MAC address to /data/misc/wifi/wlan_mac.bin, macaddrsetup needs to be in the wifi group.
=> Fixes for creating MAC address files on Oreo

rootdir/ueventd.yoshino.rc
Remove sysfs entries, replace them with the new device at
/dev/fingerprint for the new IOCTL implementation.
=> [YOSHINO] ueventd: Fix for FPC IOCTL implementation

sepolicy_platform/file_contexts
We use the oem partition to store vendor blobs and we mark the
partition as system_block_device
=> [MASTER] sepolicy: add oem partition

sepolicy_platform/file_contexts
We use the oem partition to store vendor blobs and we mark the
partition as system_block_device
=> [N-MR1] sepolicy: add oem partition

platform.mk
If the persist.camera.lib2d.rotation property is not set,
the QCamera2PostProc::encodeData() function will not
initialize the rotation value correctly, leading to
wrongly rotated images.
=> fix camera rotation bug

rootdir/init.yoshino.rc
There is a symlink from /vendor to /system/vendor.
Signed-off-by: Pavel Dubrova <pashadubrova@gmail.com>
=> yoshino: Fix service path for Android O

rootdir/init.yoshino.rc
There is a symlink from /vendor to /system/vendor.
Signed-off-by: Pavel Dubrova <pashadubrova@gmail.com>
=> [o-mr0] yoshino: Fix service path for Android O

platform.mk
those are already defined at common
=> yoshino: remove double audio props

rootdir/fstab.yoshino
After the removal of the mount for system, the build system failed to generate OTA packages, as it relies on fstab to know what to mount when executing the update script.
This reverts the removal of the lines, and adds to them the flag "recoveryonly" to avoid having Android attempt a remount of those partitions.
=> [master] fix generation of OTA packages

rootdir/fstab.yoshino
After the removal of the mount for system, the build system failed to generate OTA packages, as it relies on fstab to know what to mount when executing the update script.
This reverts the removal of the lines, and adds to them the flag "recoveryonly" to avoid having Android attempt a remount of those partitions.
=> [o-mr0] fix generation of OTA packages

rootdir/vendor/usr/idc/clearpad.idc
Changes introduced in Android 8.1.0 produced a miscalculation
of the touch pressure axis.
Change the touch pressure scale to 0.01 to prevent overflowing
and get back the touch pressure working properly, solving issues
with multi-touch gestures in various games.
Also, while at it, make sure that the device is declared as internal,
orientation aware and that the touch pressure parameter is read
from the "pressure axis" sent by the kernel driver.
=> [YOSHINO] vendor: IDC: clearpad: Fix touch pressure issues and cleanup

rootdir/vendor/etc/fstab.yoshino
On kernel 4.9, /sys/devices/soc has been moved
to /sys/devices/platform/soc.
Signed-off-by: Pavel Dubrova <pashadubrova@gmail.com>
=> [master] fstab: Update paths for k4.9

rootdir/vendor/ueventd.rc, sepolicy_platform/genfs_contexts
On kernel 4.9, /sys/devices/soc has been moved
to /sys/devices/platform/soc.
This branch for Android P+ and it uses kernel 4.9 only.
Signed-off-by: Pavel Dubrova <pashadubrova@gmail.com>
=> [master] Remove deprecated paths

rootdir/vendor/etc/wifi/wpa_supplicant_overlay.conf
Enable TDLS mode: external programs are given the control
to specify the TDLS link to get established to the driver.
Specify WoWLAN triggers to permit to keep the WiFi connected
while AP sleeps and the WLAN chip is in low power mode.
Resume the AP to handle special requests via a magic packet
sent from the WLAN chip.
=> [YOSHINO] wifi: wpa_supplicant_overlay: Declare wowlan support

rootdir/vendor/etc/fstab.yoshino, rootdir/vendor/etc/fstab_legacy.yoshino
Since there is no longer a command in init.common.rc that remounts as read-only, set the property directly in fstab.
=> [yoshino] fstab: Mount dsp partition read-only

rootdir/vendor/etc/audio_platform_info.xml
The entry for this calibration seems to be badly read or
corrupted: that makes it the kernel to send a Q6 CVP
parameter that is setting 15 RX channels and that is
obviously ... wrong.
Disable the ACDB calibration for the BT SCO WB device
at least until the database gets eventually fixed.
This PR fixes in-call BT audio
=> [YOSHINO] audio_platform_info: Disable ACDB for OUT_BT_SCO_WB

sepolicy_platform/genfs_contexts
The label was never used for anything and has been removed in the common sepolicy repo:
https://github.com/sonyxperiadev/device-sony-sepolicy/commit/ae81761d37c7d7023a1f998834f8a071ca22e8d1
=> sepolicy_platform: Remove clkscale label

platform.mk
Set primary mixer stages to 1 to force getting no blend
support from the display HAL.
This switches us from the SDE composition to the GPU
composition, which is a hack that is required for legacy
platforms on the SDE driver because of a severe
incompatibility with the current blobs.
There are no barriers because the FBDEV driver-HAL
combo have no blobs to support the SDM composition
and this configuration is anyway already doing what we
are forcing there.
=> [YOSHINO] platform: Disable SDE composition by forcing no blend

sepolicy_platform/genfs_contexts
01-01 02:14:39.368   625   625 I android.hardwar: type=1400 audit(0.0:5): avc: denied { read } for name=max_brightness dev=sysfs ino=41706 scontext=u:r:hal_light_default:s0 tcontext=u:object_r:sysfs:s0 tclass=file permissive=1
01-01 02:14:39.368   625   625 I android.hardwar: type=1400 audit(0.0:6): avc: denied { open } for path=/sys/devices/platform/soc/c900000.qcom,sde_kms/backlight/panel0-backlight/max_brightness dev=sysfs ino=41706 scontext=u:r:hal_light_default:s0 tcontext=u:object_r:sysfs:s0 tclass=file permissive=1
01-01 02:14:39.368   625   625 I android.hardwar: type=1400 audit(0.0:7): avc: denied { getattr } for path=/sys/devices/platform/soc/c900000.qcom,sde_kms/backlight/panel0-backlight/max_brightness dev=sysfs ino=41706 scontext=u:r:hal_light_default:s0 …
=> avoid sde denials

platform.mk
FBE CE switched from PBKDF2 to scrypt and these parameters were
considered optimal by Google. https://web.archive.org/web/20190511020438/https://blog.filippo.io/the-scrypt-parameters
gives an explanation of how the parameters work which were originally
set as ro.crypto.scrypt_params=16:3:1. It is furthermore defined in
system/vold.
Signed-off-by: Laster K. (lazerl0rd) <officiallazerl0rd@gmail.com>
=> yoshino: reduce cost of scrypt for FBE CE

platform.mk
As discussed in the Slack group, these definitions are insecure and should have been moved to common
anyways. Burn it with fire :).
Works alongside https://github.com/sonyxperiadev/device-sony-common/pull/627.
Signed-off-by: Laster K. (lazerl0rd) <officiallazerl0rd@gmail.com>
=> yoshino: move scrypt parameters definition to common

rootdir/vendor/ueventd.rc
On kernel 4.14 we've got a new driver for Tri-LED that adheres
...mostly... to the standard Linux way of dealing with LEDs.
Though, paths have changed!
=> [YOSHINO] ueventd: Fix Tri-LED path permissions

rootdir/vendor/firmware/wlan/qca_cld/WCNSS_qcom_cfg.ini
Configure WCNSS to expose a secondary interface, wlan1, which is used
for concurrent AP while wlan0 runs the STA.
=> [YOSHINO] WCNSS: Enable concurrent STA/AP on wlan1 interface.

PlatformConfig.mk
The service locator is now mandatory on kernel 4.14 because
it's needed for the FastRPC to find audio and sensors PDRs.
=> [YOSHINO] PlatformConfig: Enable service locator

platform.mk
This allows for apex system parts to be updated through playstore, this doesn't affect the device behaviour when there is no playstore
=> platform : Add updatble apex makefile

platform.mk, rootdir/vendor/etc/audio_policy_configuration.xml, rootdir/vendor/etc/audio_policy_configuration_bluetooth_legacy_hal.xml, rootdir/vendor/etc/common_primary_audio_policy_configuration.xml
The audio.bluetooth.default.so audio module, configured by
bluetooth_audio_policy_configuration.xml, utilizes the new HAL-based
mechanism to register a BT audio endpoint and transfer audio data.
Update our policy to route audio properly to this module, while
retaining a2dp input compatibility through the old mechanism.
See the identical change in crosshatch:
https://android.googlesource.com/device/google/crosshatch/+/c05ccdbed6c7c74d450e7149969c6c3431155628
audio_policy_configuration_bluetooth_legacy_hal.xml remains unchanged to
reflect the old variant of the system (using sockets between the BT
stack and audioserver), usable with
persist.bluetooth.bluetooth_audio_hal.disabled=true.
NOTE: This relies on device-sony-common to add the new files to
PRODUCT_COPY_FILES.
=> [YOSHINO] audio_policy: Migrate to bluetooth.audio@2.0 HAL policy

rootdir/vendor/etc/fstab.yoshino, rootdir/vendor/etc/fstab_legacy.yoshino
Calling @stefanhh for verification on lilac and @PaulBouchara for maple.
Makes things neater with the stage-separated mounting logic in Q and later.
=> fstab: Split into early and latemount, reserve 128M on /data

platform.mk
Fixes https://github.com/sonyxperiadev/bug_tracker/issues/619
This feature is required because devices in this platform do not expose
an echo-reference-voip mixer path, where -voip is concatenated when this
feature is disabled. With this feature enabled echo-reference is
selected instead, which is available and solves broken voice calls in
certain apps.
=> [YOSHINO] Enable audio compr_voip feature

platform.mk
All kernel 4.14 devices were switched to graphics "v3" (rather, from 2.1 to 2.3, with 2.4 right around the corner) but Yoshino was "forgotten" or left out (iirc because k4.14 support landed later than the other platforms?). Anyway, it's here now and required to boot R where vintf version matches are more strict; vintf has always exposed `2.3` exclusively.
---
See https://github.com/sonyxperiadev/device-sony-common/pull/667
The HAL used for kernel 4.14 (8.1 branch) exports allocator and mapper v3. Setting this property makes sure the vintf manifest represents this, in turn allowing the system to use it.
=> [YOSHINO] Enable graphics allocator and mapper v3

rootdir/vendor/etc/init/init.yoshino.pwr.rc
in the 4.14 kernel these configs are deprecated and should be removed to get rid of irrelevant errors in dmesg/logcat.
Applicable to yoshino,nile,ganges and tama
07-22 23:20:05.795     0     0 I init    : Command 'write /sys/devices/system/cpu/cpu0/cpufreq/interactive/use_migration_notif 1' action=sys.boot_completed=1 (/vendor/etc/init/init.yoshino.pwr.rc:69) took 0ms and failed: Unable to write to file '/sys/devices/system/cpu/cpu0/cpufreq/interactive/use_migration_notif': open() failed: Permission denied
07-22 23:20:05.800     0     0 I init    : Command 'write /sys/devices/system/cpu/cpu0/cpufreq/interactive/max_freq_hysteresis 79000' action=sys.boot_completed=1 (/vendor/etc/init/init.yoshino.pwr.rc:77) took 0ms and failed: Unable to write to file …
=> init.yoshino.pwr.rc: remove deprecated configs
