sonyxperiadev/device-sony-yoshino

PlatformConfig.mk

[YOSHINO] Add lpm_levels.sleep_disabled cmdline option

---

PlatformConfig.mk
platform.mk

Change-Id: Ib425d95de794e9858a626b1f3e12a29b0e30094f

yoshino: Fix miscellaneous typos

---

sepolicy_platform/file_contexts

Required for acdb.
Change-Id: I7b03c94d5ff5cac7ebbd4d14ee35458fd0b24232

[master] sony: yoshino: sepolicy: Add dsp device to file contexts

---

rootdir/fstab.yoshino
sepolicy_platform/file_contexts

recovery stuff yoshino

---

README.md
bluetooth/bdroid_buildcfg.h

yoshino: add poplar and lilac

---

rootdir/system/etc/audio_platform_info.xml

yoshino: add acdb_id for camcorder source

---

PlatformConfig.mk

According to recent build tree changes

yoshino: Enable init_sony

---

rootdir/fstab.yoshino
rootdir/init.yoshino.rc
sepolicy_platform/file_contexts
sepolicy_platform/genfs_contexts

To be merged once the new device-sony-sepolicy is complete

sepolicy improvements

---

rootdir/init.yoshino.rc

Change-Id: Id2f0e37e01bf6d46aa7f47ca205d726899914ae9

[master] sony: yoshino: Move fstab mount process to common

---

rootdir/init.yoshino.rc

commonize init stuff
Change-Id: I725747de71e9a0bb9b15b1526b13ae0eb649a7bf

[o-mr0] sony: yoshino: init: Move common stuff

---

rootdir/init.yoshino.rc

Move common init stuff between loire, tone and yoshino platforms.

[master] Move common init stuff

---

rootdir/vendor/etc/audio_platform_info.xml

Fix sonyxperiadev/bug_tracker#82.
Maple also needs this commits : https://github.com/abioteau/device-sony-maple/commit/2cc8af9fbf3540c0e1ea727fa72d28b9013bf126

[Master] Update USECASE_AUDIO_RECORD_LOW_LATENCY pcm_id

---

rootdir/vendor/etc/audio_platform_info.xml

Fix https://github.com/sonyxperiadev/bug_tracker/issues/82.
Maple also needs this commits : https://github.com/abioteau/device-sony-maple/commit/4ae46599d6736c2b6603497b4bd1bac5611eb6da

[O-mr0] Update USECASE_AUDIO_RECORD_LOW_LATENCY pcm_id

---

rootdir/system/etc/audio_platform_info.xml

Fix https://github.com/sonyxperiadev/bug_tracker/issues/82.
Maple also needs this commits : https://github.com/abioteau/device-sony-maple/commit/64b6bc8d02f33701a1909e42bb6e59acefe80559

[N-mr1] Update USECASE_AUDIO_RECORD_LOW_LATENCY pcm_id

---

PlatformConfig.mk
rootdir/vendor/etc/init/init.yoshino.rc

wifi: use driver state control

---

rootdir/vendor/etc/fstab.yoshino

Bug: 30807864
Change-Id: If3f67d5b7b15409c2717ef0d92851ca46677e4ff

Remove discard in fstab

---

rootdir/vendor/etc/fstab.yoshino
sepolicy_platform/file_contexts

fstab: declare /vendor partition

---

rootdir/vendor/etc/audio_platform_info.xml

removed not existent SDN_DEVICES

audio: cleanup audio_platform_info

---

rootdir/vendor/etc/fstab.yoshino

Bug: 38351804
Test: boot
Change-Id: Ibe884310960f88ce7dd757a50b232fc70ae89274

Add quota support to data partition

---

rootdir/vendor/etc/rqbalance_config.xml

Add the configuration for the sustained performance power hint
and update the other configurations to use RQB-CFL where possible
to achieve better performance for app opening and better battery
life in batterysave cases.

[YOSHINO] rqbalance_config: Update configuration for RQB-CFL and sustained

---

rootdir/vendor/etc/init/init.yoshino.pwr.rc

the same driver same paths are used by all platforms move it to common repo

PowerHal: move all needed perm to common
